cargo-features = ["edition2024"]

[package]
name = "rs-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.19"
shell-words = "1.1.0"
tokio = { version = "1", features = ["full"] }